### ISSUE TITLE
[DOC] Add more info on how to manage large messages

### ISSUE THREAD

**Issue by Simonbdy** [Luos-io/Documentation#111]
**Insert the documentation link:**
https://docs.luos.io/pages/low/containers/msg-handling.html#large-data

**Describe the issue or the suggestion:**
The page needs more information on how Luos manages large messages.

**How would you fix the issue / which content would you add or delete?**
Add description

**Comment by BiliouriV** [comment]
I propose something like the following for this doc page:

_In first paragraph:_
You will sometimes have to deal with large data, that could be larger than the maximum 128-byte data on a Luos message. Fortunately, Luos is able to automatically fragment and de-fragment the data above this side. To do that, instead of using Luos_SendMsg() function, you will have to use the Luos_SendData() function, that will take care of setting the messages' size, and the data fields. In other words, this function is responsible for separating each message with data size larger than 128 bytes, to multiple messages, with the size parameter equal to the full data size, decremented by the size of the data that have already been send. 
For instance, if we have a message with data size equal to 256 bytes, it will be divided in 2 separated messages of 128 bytes of data each, with almost the same header, apart from the size field of the header, which for the first message will be equal to 256 and for the second message will be equal to 128.

_After the 2 code windows about sending an image:_

In the above example the send function used, sent the pixels of the image in multiple messages of 128-byte data and the receive function rejoined the full image after receiving each separated message.

**Comment by Simonbdy** [comment]
Fixed with https://github.com/Luos-io/Documentation/commit/da6df20479b9b6dac86fc22a45eed5091a411a25
